[package]
name = "fun_with_hashes"
version = "0.1.0"
authors = ["Orlando Mendez <mmoa33@hotmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
