name: Rust

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Build
      run: cargo build --verbose --manifest-path functions/Cargo.toml
           cargo build --verbose --manifest-path ownership/Cargo.toml

    # - name: Run tests
    #   run: cargo test --verbose
